# Generated by Django 4.0.4 on 2022-06-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=60)),
                ('prw_product', models.ImageField(default='static/product/default.webp', upload_to='static/product')),
            ],
        ),
        migrations.CreateModel(
            name='Subproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproduct', models.CharField(max_length=60)),
                ('prw_subproduct', models.ImageField(default='static/subproduct/default.webp', upload_to='static/subproduct')),
                ('text_subproduct', models.TextField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outdoor.product')),
            ],
        ),
    ]
