# Generated by Django 4.0.4 on 2022-06-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoor', '0002_subproduct_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='static/portfolio/default.webp', upload_to='static/portfolio')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
